name: Deploy Okanban 

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - names: checkout code
      - uses: actions/checkout@v3

     - name: Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci 
        working-directory: front

      - name: Build the project
        run: npm run build
        working-directory: front

      - name: Build Front Images
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/okanban_front_v1:latest .
        working-directory: front

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Push Front Images
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/okanban_front_v1:latest
        working-directory: front

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          npx railway up --project okanban-api --env production